#!/usr/bin/env bash
#MISE description="Resets backends across all folders.  Used as a standalone call or with bootstrap-backend to reset branch backend.tf files"
#MISE hide=true

set -eo pipefail

directories=(
  "infrastructure/demo"
  "infrastructure/demo-nowiz"
)

process_directory() {
  local dir="$1"
  if [[ $dir == *"/modules/"* ]]; then
    return
  fi

  if [[ -n $(find "$dir" -maxdepth 1 -name "*.tf") ]]; then
    if [[ -f "$dir/backend.hcl" ]]; then
      echo "[INFO]: Found backend config in $dir.  Removing"
      rm "$dir/backend.hcl"
    fi

  else
    for subdir in "$dir"/*; do
      if [[ -d $subdir ]]; then
        process_directory "$subdir"
      fi
    done
  fi
}

for base_dir in "${directories[@]}"; do
  full_path="$GIT_ROOT/$base_dir"
  process_directory "$full_path"
done
